version: '3'

services:
  dudoxx-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dudoxx-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - dudoxx-network
    command: run

  redis:
    image: redis:alpine
    container_name: dudoxx-redis
    ports:
      - "6379:6379"
    networks:
      - dudoxx-network

  dudoxx-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/share/nginx/html
      - /usr/share/nginx/html/node_modules
    ports:
      - "8080:80"
    networks:
      - dudoxx-network

networks:
  dudoxx-network: