version: '3'

services:
  pg_vector:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: dudoxx
      POSTGRES_PASSWORD: dudoxx
      POSTGRES_DB: dudoxx
    ports:
      - "5433:5432"
    volumes:
      - dudoxx-data:/var/lib/postgresql/data
    networks:
      - dudoxx-network

  dudoxx-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dudoxx-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - dudoxx-network
    command: run

  redis:
    image: redis:alpine
    container_name: dudoxx-redis
    ports:
      - "6379:6379"
    networks:
      - dudoxx-network

networks:
  dudoxx-network:

volumes:
  dudoxx-data:
